apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: database
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: mysql
          image: "mysql:5.7"
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: wordpress
            - name: MYSQL_USER
              value: wp
            - name: MYSQL_ROOT_HOST
              value: '%'  
            - name: MYSQL_PASSWORD
              value: wordpress
